#include<iostream>
using namespace std;
int main()
{
   // cout<<"hello this is ritesh swami !!";

// new line print
    {              // just to seperate things

// //  method 1 :    
//     cout<<"hello this is ";
//     cout<<endl;
//     cout<<"ritesh swami !!";

// //  method 2:
//     cout<<"hello this is "<<endl<<"ritesh swami !!";

//  method 3 :
    // cout<<"hello this is \nritesh swami !!";

    }

// cout 
    {
    
    cout<<4+7<<endl;
    cout<<"4+7";
    
    }

}